# Generated by Django 4.2.19 on 2025-02-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_alter_cook_options_alter_dish_dish_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
