# Generated by Django 4.2.19 on 2025-02-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0003_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cook",
            options={
                "ordering": ["username"],
                "verbose_name": "cook",
                "verbose_name_plural": "cooks",
            },
        ),
    ]
